version: '3'

services:
  mySQL:
    image: mysql:latest
    restart: "always"
    container_name: mydb
    environment:
      - "MYSQL_ROOT_PASSWORD=password123"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=password123"
      - "MYSQL_DATABASE=canchas_datamodel"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"